### ISSUE TITLE
Document for installation.

### ISSUE THREAD

**Issue by jeesim2** [asalih/elasticsearch-lim#1]
Hello.

Now I am interest of this application.
It looks simple but have fairly important monitoring features.

BTW, Could you please write up some startup tutorial?
A little go build and running app tutorial will be a great help.
(I have no experience with Go lang)

Thanks!

**Comment by asalih** [comment]
Hello, I assume that you have allready installed golang successfully.

Example for windows:
1. Open cmd and execute "go get -u github.com/asalih/elasticsearch-lim". It downloads all package and its dependencies
2. On cmd, change directory to gopath, find downloaded folder or execute 
"cd %gopath%\src\github.com\asalih\elasticsearch-lim"
3. Run "go build main.go"
4. You build the app, now check the ".env" file. Make the required changes.
5. Execute main.exe. It will setup new Index to target and keeps data there.

Thanks for your feedback!
